### PR TITLE
Added a test for loading empty model to wasi-nn

### PR DESCRIPTION
**Pull request by Mossaka**
Added a simple loading-empty-model test to the wasi-nn PR: #4

### CODE REVIEW

**Comment by radu-matei** [comment]
Given that #4 is not merged yet, would you mind targeting that?

**Comment by radu-matei** [comment]
Ok, let me first merge #4, then you can rebase (and squash some of the conflicts commits).

**Comment by radu-matei** [comment]
Ok, #4 has now been merged.

**Comment by Mossaka** [comment]
Alright, thanks @radu-matei . I think it's ready to be reviewed.

**Review by radu-matei — APPROVED** [review]
I think this needs a `rustfmt` and it should be good to go.

**Comment by Mossaka** [comment]
@radu-matei do we need a non-trivial test, similar to the squeezenet we used before?

**Comment by radu-matei** [comment]
Perhaps just an identity model would suffice.
Let's have that as a follow-up PR.
Thanks a lot!

**Pull request merged**
